In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [1]:
print("Hello, World!")

Hello, World!

In [4]:
pd.__version__

'3.0.6'

In [5]:
# Load the dataset
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [6]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [7]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

In [13]:
# Records Count

print(len(df))

10000

In [14]:
# Records Count

print(df.shape[0])

10000

In [ ]:
# Fuel types

df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [18]:
# Missing values

print(df.isna().sum())

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [27]:
# What's the maximum fuel efficiency of cars from Asia?

print(df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max())

41.2

In [21]:
df['origin']

0       Europe
1       Europe
2         Asia
3       Europe
4          USA
         ...
9995       USA
9996      Asia
9997       USA
9998       USA
9999       USA
Name: origin, Length: 10000, dtype: str

In [41]:
# Q6. Median value of horsepower

# Find the median value of the horsepower column in the dataset.
# Next, calculate the most frequent value of the same horsepower column.
# Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
# Now, calculate the median value of horsepower once again.

median = df['horsepower'].median()
print(median)
frequent = df['horsepower'].mode()[0]
print(frequent)
df['horsepower'] = df['horsepower'].fillna(frequent, inplace=True)
print(df['horsepower'].median())

254.0
252.0
252.0

/var/folders/04/vl3jr1ks0897h39z7nrwl_8m0000gn/T/ipykernel_81576/3102988578.py:12: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['horsepower'] = df['horsepower'].fillna(frequent, inplace=True)

In [42]:
print(df['horsepower'].isna().sum())

0

In [43]:
# Q7. Sum of weights

# Select all the cars from Asia
df_asia = df[df['origin'] == 'Asia']

# Select only columns vehicle_weight and model_year
df_asia_subset = df_asia[['vehicle_weight', 'model_year']]

# Select the first 7 values
df_asia_first_7 = df_asia_subset.head(7)

# Get the underlying NumPy array. Let's call it X.
X = df_asia_first_7.values

# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = np.dot(X.T, X)

# Invert XTX.
XTX_inv = np.linalg.inv(XTX)

# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = np.dot(np.dot(XTX_inv, X.T), y)

# What's the sum of all the elements of the result?

sum_w = np.sum(w)
print(sum_w)

0.36919696904925203